apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

type: Opaque
data:
  maria-db-user: "{{ .Values.database.user | b64enc }}"
  maria-db-password: "{{ .Values.database.password | b64enc }}"
  maria-db-port: "{{ .Values.database.port | b64enc }}"
